import { StyleSheet } from 'react-native';
import { SoundMateLightColors } from '../../../constants/theme';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: SoundMateLightColors.background,
    },
    mainTabViewport: {
        flex: 1,
        position: 'relative',
        overflow: 'hidden',
    },
    mainTabPage: {
        ...StyleSheet.absoluteFillObject,
    },
    searchScreen: {
        flex: 1,
    },
    searchHeader: {
        paddingHorizontal: 14,
        paddingTop: 12,
        paddingBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomWidth: 1,
    },
    searchBackButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchInputWrap: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 14,
        borderWidth: 1,
        paddingHorizontal: 10,
        marginHorizontal: 8,
        minHeight: 42,
    },
    searchInput: {
        flex: 1,
        fontSize: 14,
        marginLeft: 8,
        marginRight: 8,
    },
    searchInputFieldWrap: {
        flex: 1,
    },
    searchGoButton: {
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 9,
    },
    searchGoText: {
        color: '#FFFFFF',
        fontWeight: '700',
        fontSize: 12,
    },
    searchBodyContent: {
        paddingHorizontal: 16,
        paddingTop: 14,
        paddingBottom: 120,
    },
    searchSectionTitle: {
        fontSize: 18,
        fontWeight: '800',
        marginBottom: 12,
    },
    searchSubTitle: {
        fontSize: 15,
        fontWeight: '700',
        marginBottom: 8,
    },
    searchHintText: {
        fontSize: 13,
        lineHeight: 18,
    },
    searchLoadingBlock: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 20,
        gap: 8,
    },
    suggestionCard: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 14,
        borderWidth: 1,
        padding: 10,
        marginBottom: 8,
    },
    suggestionImage: {
        width: 42,
        height: 42,
        borderRadius: 10,
        marginRight: 10,
    },
    suggestionImageFallback: {
        width: 42,
        height: 42,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
    },
    suggestionInfo: {
        flex: 1,
    },
    suggestionTitle: {
        fontSize: 14,
        fontWeight: '700',
        marginBottom: 2,
    },
    suggestionSubtitle: {
        fontSize: 12,
    },
    suggestionTag: {
        borderRadius: 999,
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    suggestionTagText: {
        fontSize: 10,
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    suggestionFavoriteButton: {
        width: 28,
        height: 28,
        borderRadius: 999,
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchFallbackButton: {
        marginTop: 12,
        borderWidth: 1,
        borderRadius: 12,
        paddingVertical: 10,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 6,
    },
    searchFallbackText: {
        fontSize: 13,
        fontWeight: '600',
    },
    searchResultHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 4,
    },
    searchBackToSuggestText: {
        fontSize: 12,
        fontWeight: '600',
    },
    searchSectionWrap: {
        marginTop: 14,
    },
    resultRowCard: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 12,
        borderWidth: 1,
        padding: 10,
        marginBottom: 8,
    },
    resultRowImage: {
        width: 44,
        height: 44,
        borderRadius: 10,
        marginRight: 10,
    },
    resultRowInfo: {
        flex: 1,
    },
    resultRowTitle: {
        fontSize: 14,
        fontWeight: '700',
        marginBottom: 2,
    },
    resultRowSubtitle: {
        fontSize: 12,
    },
    scrollContent: {
        paddingBottom: 114,
    },
    header: {
        paddingHorizontal: 16,
        paddingTop: 6,
        paddingBottom: 20,
        borderBottomLeftRadius: 22,
        borderBottomRightRadius: 22,
        overflow: 'hidden',
        marginBottom: 6,
    },
    headerGlowTop: {
        position: 'absolute',
        width: 210,
        height: 210,
        borderRadius: 105,
        backgroundColor: 'rgba(255,255,255,0.13)',
        top: -70,
        right: -55,
    },
    headerGlowBottom: {
        position: 'absolute',
        width: 180,
        height: 180,
        borderRadius: 90,
        backgroundColor: 'rgba(255,255,255,0.09)',
        bottom: -85,
        left: -40,
    },
    topBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    brandWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        position: 'relative',
        top: 4,
    },
    brandLogoIcon: {
        width: 60,
        height: 60,
    },
    brandLogoText: {
        position: 'relative',
        bottom: 4,
        right: 10,
        width: 104,
        height: 34,
    },
    headerIcons: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerIconButton: {
        width: 38,
        height: 38,
        borderRadius: 19,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255,255,255,0.18)',
        marginLeft: 8,
    },
    heroContent: {
        marginTop: 10,
        paddingHorizontal: 4,
    },
    heroEyebrow: {
        color: 'rgba(255,255,255,0.8)',
        fontSize: 10,
        fontWeight: '700',
        letterSpacing: 0.9,
        marginBottom: 6,
    },
    heroTitle: {
        color: '#FFFFFF',
        fontSize: 26,
        fontWeight: '900',
        marginBottom: 8,
    },
    heroSubtitle: {
        color: 'rgba(255,255,255,0.92)',
        fontSize: 13,
        lineHeight: 19,
        marginBottom: 14,
    },
    quickActionRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    quickActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.2)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.22)',
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 7,
        marginRight: 8,
    },
    quickActionText: {
        marginLeft: 5,
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '700',
    },
    liveBannerContainer: {
        marginTop: 12,
        marginBottom: 14,
        marginHorizontal: 16,
        borderRadius: 22,
        overflow: 'hidden',
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.2,
        shadowRadius: 18,
        elevation: 9,
    },
    liveBanner: {
        height: 218,
        alignItems: 'stretch',
        justifyContent: 'flex-start',
        paddingHorizontal: 20,
        paddingVertical: 16,
        position: 'relative',
    },
    liveBannerAuraTop: {
        position: 'absolute',
        top: -85,
        right: -48,
        width: 180,
        height: 180,
        borderRadius: 90,
        backgroundColor: 'rgba(255,255,255,0.14)',
    },
    liveBannerAuraBottom: {
        position: 'absolute',
        bottom: -92,
        left: -60,
        width: 190,
        height: 190,
        borderRadius: 95,
        backgroundColor: 'rgba(255,255,255,0.1)',
    },
    livePill: {
        alignSelf: 'flex-start',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#EF4444',
        paddingHorizontal: 14,
        paddingVertical: 7,
        borderRadius: 999,
        marginBottom: 12,
        zIndex: 2,
    },
    livePillDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#FFFFFF',
        marginRight: 7,
    },
    livePillText: {
        fontSize: 12,
        fontWeight: '800',
        color: '#FFFFFF',
    },
    liveBannerTitle: {
        zIndex: 2,
        fontSize: 21,
        fontWeight: '800',
        color: '#FFFFFF',
        lineHeight: 28,
        marginBottom: 5,
    },
    liveBannerHost: {
        zIndex: 2,
        fontSize: 12,
        color: 'rgba(255,255,255,0.95)',
        marginBottom: 8,
    },
    liveBannerMainRow: {
        zIndex: 2,
        flexDirection: 'row',
        alignItems: 'flex-end',
        justifyContent: 'space-between',
    },
    liveBannerMainInfo: {
        flex: 1,
        paddingRight: 10,
    },
    liveBannerMeta: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    liveBannerMetaText: {
        marginLeft: 4,
        color: 'rgba(255,255,255,0.92)',
        fontSize: 11,
        fontWeight: '500',
    },
    liveStatCard: {
        width: 88,
        borderRadius: 14,
        backgroundColor: 'rgba(255,255,255,0.18)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.22)',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
    },
    liveStatValue: {
        color: '#FFFFFF',
        fontSize: 17,
        fontWeight: '900',
        marginTop: 4,
    },
    liveStatLabel: {
        color: 'rgba(255,255,255,0.9)',
        fontSize: 10,
        fontWeight: '600',
    },
    liveBannerFooterRow: {
        zIndex: 2,
        marginTop: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    liveWaveBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 999,
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
        paddingHorizontal: 10,
        paddingVertical: 7,
        marginRight: 8,
        flex: 1,
    },
    liveWaveBadgeText: {
        marginLeft: 5,
        color: '#FFFFFF',
        fontSize: 10,
        fontWeight: '600',
    },
    liveBannerButton: {
        borderRadius: 999,
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 14,
        paddingVertical: 8,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    liveBannerButtonText: {
        color: '#0F172A',
        fontSize: 12,
        fontWeight: '800',
    },
    liveBannerOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.16)',
    },
    sectionBlock: {
        paddingTop: 12,
        paddingBottom: 10,
    },
    topHitSection: {
        paddingTop: 12,
        paddingBottom: 14,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 21,
        fontWeight: '800',
    },
    seeAllText: {
        fontSize: 12,
        fontWeight: '700',
        color: SoundMateLightColors.primary,
    },
    horizontalScrollContent: {
        paddingHorizontal: 20,
    },
    topHitScrollContent: {
        paddingHorizontal: 20,
    },
    topHitCard: {
        width: 226,
        height: 166,
        borderRadius: 20,
        overflow: 'hidden',
        marginRight: 12,
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.18,
        shadowRadius: 14,
        elevation: 6,
    },
    topHitCardImage: {
        ...StyleSheet.absoluteFillObject,
        width: '100%',
        height: '100%',
    },
    topHitCardOverlay: {
        ...StyleSheet.absoluteFillObject,
    },
    topHitRankBadge: {
        position: 'absolute',
        top: 10,
        left: 10,
        backgroundColor: 'rgba(255,255,255,0.2)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.28)',
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 5,
    },
    topHitRankText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '900',
    },
    topHitPlayButton: {
        position: 'absolute',
        top: 10,
        right: 10,
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(37,99,235,0.95)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    topHitMetaWrap: {
        position: 'absolute',
        left: 12,
        right: 12,
        bottom: 12,
    },
    topHitTitle: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '800',
        marginBottom: 6,
    },
    topHitStatsRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    topHitStatsText: {
        marginLeft: 5,
        color: 'rgba(255,255,255,0.95)',
        fontSize: 11,
        fontWeight: '600',
    },
    topHitDot: {
        width: 4,
        height: 4,
        borderRadius: 2,
        backgroundColor: 'rgba(255,255,255,0.65)',
        marginHorizontal: 7,
    },
    topHitCategoryText: {
        color: 'rgba(255,255,255,0.9)',
        fontSize: 11,
        fontWeight: '700',
    },
    playlistTabScrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 12,
    },
    playlistTabChip: {
        borderRadius: 999,
        paddingHorizontal: 15,
        paddingVertical: 9,
        marginRight: 8,
    },
    playlistTabChipText: {
        fontSize: 12,
        fontWeight: '700',
    },
    playlistFeaturedCard: {
        marginHorizontal: 20,
        height: 184,
        borderRadius: 20,
        overflow: 'hidden',
        marginBottom: 12,
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.16,
        shadowRadius: 14,
        elevation: 5,
    },
    playlistFeaturedImage: {
        ...StyleSheet.absoluteFillObject,
        width: '100%',
        height: '100%',
    },
    playlistFeaturedOverlay: {
        ...StyleSheet.absoluteFillObject,
    },
    playlistFeaturedBadge: {
        position: 'absolute',
        top: 12,
        left: 12,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.2)',
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    playlistFeaturedBadgeText: {
        color: '#FFFFFF',
        fontSize: 11,
        fontWeight: '700',
        marginLeft: 5,
    },
    playlistFeaturedInfo: {
        position: 'absolute',
        left: 14,
        right: 14,
        bottom: 14,
    },
    playlistFeaturedTitle: {
        color: '#FFFFFF',
        fontSize: 20,
        fontWeight: '900',
        marginBottom: 4,
    },
    playlistFeaturedSubtitle: {
        color: 'rgba(255,255,255,0.92)',
        fontSize: 13,
        marginBottom: 10,
    },
    playlistFeaturedFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    playlistFeaturedChip: {
        borderRadius: 999,
        backgroundColor: 'rgba(255,255,255,0.2)',
        paddingHorizontal: 11,
        paddingVertical: 6,
    },
    playlistFeaturedChipText: {
        color: '#FFFFFF',
        fontSize: 11,
        fontWeight: '700',
    },
    playlistFeaturedPlayButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    myPlaylistCard: {
        width: 164,
        marginRight: 12,
        borderRadius: 16,
        borderWidth: 1,
        overflow: 'hidden',
    },
    myPlaylistImageWrap: {
        width: '100%',
        height: 114,
    },
    myPlaylistImage: {
        width: '100%',
        height: '100%',
    },
    myPlaylistOverlay: {
        ...StyleSheet.absoluteFillObject,
    },
    myPlaylistCategoryBadge: {
        position: 'absolute',
        top: 8,
        left: 8,
        borderRadius: 999,
        backgroundColor: 'rgba(255,255,255,0.2)',
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    myPlaylistCategoryText: {
        color: '#FFFFFF',
        fontSize: 10,
        fontWeight: '700',
    },
    myPlaylistPlayButton: {
        position: 'absolute',
        right: 8,
        bottom: 8,
        width: 30,
        height: 30,
        borderRadius: 15,
        alignItems: 'center',
        justifyContent: 'center',
    },
    myPlaylistMeta: {
        paddingHorizontal: 10,
        paddingVertical: 9,
    },
    myPlaylistTitle: {
        fontSize: 13,
        fontWeight: '800',
        marginBottom: 2,
    },
    myPlaylistSubtitle: {
        fontSize: 11,
    },
    playlistCard: {
        width: 152,
        marginRight: 14,
    },
    playlistImageWrapper: {
        width: 152,
        height: 152,
        borderRadius: 20,
        overflow: 'hidden',
        backgroundColor: '#D1D5DB',
        marginBottom: 10,
    },
    playlistImage: {
        width: '100%',
        height: '100%',
    },
    playlistOverlay: {
        ...StyleSheet.absoluteFillObject,
    },
    playIconButton: {
        position: 'absolute',
        top: 10,
        right: 10,
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: SoundMateLightColors.primary,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: SoundMateLightColors.primary,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.32,
        shadowRadius: 8,
        elevation: 5,
    },
    playIcon: {
        marginLeft: 1,
    },
    playlistTitleContainer: {
        position: 'absolute',
        left: 8,
        right: 8,
        bottom: 8,
    },
    playlistTitle: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '800',
    },
    playlistSubtitle: {
        fontSize: 12,
        color: SoundMateLightColors.textSecondary,
        textAlign: 'left',
        marginLeft: 2,
    },
    podcastSection: {
        marginTop: 12,
        paddingTop: 12,
        paddingBottom: 16,
        borderRadius: 20,
        marginHorizontal: 12,
    },
    podcastFeaturedCard: {
        marginHorizontal: 20,
        height: 174,
        borderRadius: 20,
        overflow: 'hidden',
        marginBottom: 12,
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.16,
        shadowRadius: 14,
        elevation: 5,
    },
    podcastFeaturedImage: {
        ...StyleSheet.absoluteFillObject,
        width: '100%',
        height: '100%',
    },
    podcastFeaturedOverlay: {
        ...StyleSheet.absoluteFillObject,
    },
    podcastFeaturedHeader: {
        position: 'absolute',
        top: 12,
        left: 12,
        right: 12,
        flexDirection: 'row',
        justifyContent: 'flex-start',
    },
    podcastFeaturedBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 999,
        backgroundColor: 'rgba(255,255,255,0.2)',
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    podcastFeaturedBadgeText: {
        color: '#FFFFFF',
        fontSize: 11,
        fontWeight: '700',
        marginLeft: 5,
    },
    podcastFeaturedInfo: {
        position: 'absolute',
        left: 14,
        right: 14,
        bottom: 14,
    },
    podcastFeaturedTitle: {
        color: '#FFFFFF',
        fontSize: 20,
        fontWeight: '900',
        marginBottom: 4,
    },
    podcastFeaturedHost: {
        color: 'rgba(255,255,255,0.92)',
        fontSize: 12,
        marginBottom: 10,
    },
    podcastFeaturedFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    podcastFeaturedMetaChip: {
        borderRadius: 999,
        backgroundColor: 'rgba(255,255,255,0.2)',
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    podcastFeaturedMetaChipText: {
        color: '#FFFFFF',
        fontSize: 11,
        fontWeight: '700',
    },
    podcastFeaturedPlayCta: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 999,
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    podcastFeaturedPlayCtaText: {
        color: '#0F172A',
        fontSize: 11,
        fontWeight: '800',
        marginLeft: 4,
    },
    podcastHotCard: {
        width: 164,
        marginRight: 12,
        borderRadius: 16,
        borderWidth: 1,
        overflow: 'hidden',
    },
    podcastHotImageWrap: {
        width: '100%',
        height: 114,
    },
    podcastHotImage: {
        width: '100%',
        height: '100%',
    },
    podcastHotOverlay: {
        ...StyleSheet.absoluteFillObject,
    },
    podcastHotPlayButton: {
        position: 'absolute',
        right: 8,
        bottom: 8,
        width: 30,
        height: 30,
        borderRadius: 15,
        alignItems: 'center',
        justifyContent: 'center',
    },
    podcastHotMeta: {
        paddingHorizontal: 10,
        paddingVertical: 9,
    },
    podcastHotTitle: {
        fontSize: 13,
        fontWeight: '800',
        marginBottom: 2,
    },
    podcastHotHost: {
        fontSize: 11,
    },
    scheduleSection: {
        marginTop: 8,
        paddingBottom: 6,
    },
    schedulePanel: {
        marginHorizontal: 12,
        borderRadius: 18,
        paddingVertical: 10,
        paddingHorizontal: 8,
    },
    scheduleCard: {
        marginHorizontal: 8,
        marginBottom: 10,
        borderRadius: 16,
        borderWidth: 1,
        paddingHorizontal: 10,
        paddingVertical: 11,
        flexDirection: 'row',
        alignItems: 'stretch',
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 7,
        elevation: 2,
    },
    scheduleTimelineCol: {
        width: 16,
        alignItems: 'center',
        marginRight: 8,
    },
    scheduleTimelineDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        marginTop: 6,
    },
    scheduleTimelineLine: {
        width: 2,
        flex: 1,
        marginTop: 4,
        marginBottom: -14,
    },
    scheduleContentWrap: {
        flex: 1,
        marginRight: 8,
    },
    scheduleTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
    },
    scheduleStatusPill: {
        marginLeft: 8,
        borderRadius: 999,
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    scheduleStatusText: {
        fontSize: 10,
        fontWeight: '700',
    },
    scheduleTime: {
        fontSize: 15,
        fontWeight: '800',
    },
    scheduleTitle: {
        fontSize: 14,
        fontWeight: '700',
        marginBottom: 3,
    },
    scheduleHost: {
        fontSize: 11,
    },
    scheduleActionCol: {
        justifyContent: 'center',
    },
    scheduleAction: {
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 8,
        minWidth: 74,
        alignItems: 'center',
        justifyContent: 'center',
        maxHeight: 32,
    },
    scheduleActionText: {
        fontSize: 11,
        fontWeight: '700',
    },
    podcastCard: {
        width: 154,
        marginRight: 12,
        alignItems: 'flex-start',
        borderRadius: 16,
        padding: 10,
        borderWidth: 1,
    },
    podcastImageFrame: {
        width: 134,
        height: 134,
        borderRadius: 14,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.8)',
        backgroundColor: '#D1D5DB',
        overflow: 'hidden',
        marginBottom: 9,
        shadowColor: '#0EA5E9',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.24,
        shadowRadius: 11,
        elevation: 4,
    },
    podcastImage: {
        width: '100%',
        height: '100%',
    },
    podcastTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: SoundMateLightColors.textPrimary,
        textAlign: 'left',
        paddingHorizontal: 2,
    },
    podcastHost: {
        marginTop: 2,
        fontSize: 12,
        color: SoundMateLightColors.textSecondary,
        textAlign: 'left',
        paddingHorizontal: 2,
    },
    communitySection: {
        paddingHorizontal: 16,
        paddingTop: 14,
    },
    premiumCard: {
        borderRadius: 18,
        padding: 18,
        marginBottom: 16,
        overflow: 'hidden',
    },
    premiumGlow: {
        position: 'absolute',
        width: 180,
        height: 180,
        borderRadius: 90,
        backgroundColor: 'rgba(255,255,255,0.18)',
        top: -80,
        right: -54,
    },
    premiumTag: {
        fontSize: 11,
        fontWeight: '800',
        marginBottom: 6,
    },
    premiumTitle: {
        fontSize: 19,
        fontWeight: '800',
        color: '#FFFFFF',
        marginBottom: 9,
        maxWidth: '86%',
    },
    premiumDesc: {
        fontSize: 12,
        lineHeight: 19,
        marginBottom: 14,
        maxWidth: '86%',
    },
    premiumButton: {
        alignSelf: 'flex-start',
        borderRadius: 999,
        paddingHorizontal: 14,
        paddingVertical: 9,
    },
    premiumButtonText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '800',
    },
    communityLoadingWrap: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 18,
    },
    communityLoadingText: {
        marginTop: 8,
        fontSize: 12,
        color: SoundMateLightColors.textSecondary,
    },
    communityEmptyText: {
        fontSize: 13,
        color: SoundMateLightColors.textMuted,
        textAlign: 'center',
        paddingVertical: 16,
    },
    forumCard: {
        backgroundColor: SoundMateLightColors.surface,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        padding: 13,
        marginBottom: 13,
    },
    forumAuthorRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    forumAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: SoundMateLightColors.primary,
        marginRight: 10,
    },
    forumAuthorInfo: {
        flex: 1,
    },
    forumAuthorNameRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 2,
    },
    forumAuthorName: {
        maxWidth: '60%',
        fontSize: 13,
        fontWeight: '700',
        color: SoundMateLightColors.textPrimary,
        marginRight: 8,
    },
    forumBadge: {
        borderRadius: 999,
        paddingHorizontal: 8,
        paddingVertical: 3,
    },
    forumBadgeText: {
        color: '#FFFFFF',
        fontSize: 9,
        fontWeight: '800',
    },
    forumTime: {
        fontSize: 10,
        color: SoundMateLightColors.textMuted,
    },
    forumPostTitle: {
        fontSize: 14,
        color: SoundMateLightColors.textPrimary,
        lineHeight: 20,
        marginBottom: 10,
    },
    forumActionRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    forumActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F3F4F6',
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 6,
        marginRight: 8,
    },
    forumActionText: {
        marginLeft: 5,
        fontSize: 12,
        fontWeight: '600',
        color: SoundMateLightColors.textPrimary,
    },
});

export default styles;

